<?php
use League\Flysystem\Filesystem;
use League\Flysystem\ZipArchive\ZipArchiveAdapter;



class Zip_Process extends WP_Background_Process {

	protected $action = 'zip_process';
	/**
	 * @var Filesystem
	 */
protected $zip_archive;
	public function __construct() {
		parent::__construct();
		$this->zip_archive = new Filesystem( new ZipArchiveAdapter( '/srv/www/wordpress-default/archive-' . md5(time()) . '.zip' ) );



	}

	protected function task( $item ) {
		error_log($item);
		try{
			$this->zip_archive->write( $item );
		} catch( \Exception $e){
			error_log($e);
		}


		return false;
	}

	protected function complete() {
		parent::complete(); // TODO: Change the autogenerated stub
	}
}
